---
name: environment dependent workflow final
on:
  workflow_dispatch: 
    inputs:
      environment:
        description: this is the env value where this workflow run
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code 
        run: echo "checkout code"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build the code 
        run: echo "build container image"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the code 
        run: echo "test the code"
  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy the code 
        run: echo "deploy the code"
